# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0002_auto_20170314_1630'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='like',
            name='author',
        ),
        migrations.RemoveField(
            model_name='like',
            name='target_type',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
